# Generated by Django 5.2.4 on 2025-08-12 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0003_question_activity_type_activity_video_url_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facerecord',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_records', to='faces.activity'),
        ),
        migrations.AddField(
            model_name='facerecord',
            name='phase',
            field=models.CharField(blank=True, choices=[('video', 'video'), ('quiz', 'quiz')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='facerecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
